### ISSUE TITLE
Issue for Nm timer @ pnm

### ISSUE THREAD

**Issue by RsFoe** [dey0/pluginhub-plugins#8]
The first image below is the timers from a complete kill, listed in the order they are posted during the kill. 
The second image is a full kill in order from the second kill of a trip (b2b kills)

Hopefully this helps demonstrate whats wrong with it and makes it easy. Appreciate your work and if theres something else I can test to get this working let me know :)

https://i.imgur.com/oWMHVdn.png
https://i.imgur.com/PXoHKnm.png

**Comment by dey0** [comment]
Did you turn the plugin on after entering the room? That could be the issue

**Comment by RsFoe** [comment]
nah I downloaded it and turned it on right away

**Comment by dey0** [comment]
Going to leave the issue open for now until someone can second the issue and provide more details.

**Comment by zhedax** [comment]
Hi! I can confirm that I had similar issues both in nm and pnm when I tried testing plugin when it was added to plugin hub. Removed plugins and installed it again before entering any of the bosses and issues remained.

**Comment by zhedax** [comment]
> Hi! I can confirm that I had similar issues both in nm and pnm when I tried testing plugin when it was added to plugin hub. Removed plugins and installed it again before entering any of the bosses and issues remained.

https://i.imgur.com/mQ4l2R3.png
https://i.imgur.com/BCFYoeg.png
